### ISSUE TITLE
Error: Cannot find module 'C:\Users\dig0w\OneDrive\Documentos\GitHub\bot-test\node_modules\disco-oauth\index.js'. Please verify that the package.json has a valid "main" entry

### ISSUE THREAD

**Issue by Dig0w** [disco-oauth/disco-oauth#30]
Error: Cannot find module 'C:\Users\dig0w\OneDrive\Documentos\GitHub\bot-test\node_modules\disco-oauth\index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:321:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:682:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:952:27)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\dig0w\OneDrive\Documentos\GitHub\bot-test\app\auth-client.js:1:21)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32) {
  code: 'MODULE_NOT_FOUND',
  path: 'C:\\Users\\dig0w\\OneDrive\\Documentos\\GitHub\\bot-test\\node_modules\\disco-oauth\\package.json',
  requestPath: 'disco-oauth'
}

I am trying to create a website for a Discord bot.
And he would use "disco-oauth" for the user to enter the Discord account.

The app is not starting.

https://cdn.discordapp.com/attachments/634794270104092714/806938955625791488/unknown.png

node.js: `12.18.4`
disco-oauth: `^5.0.0`

**Comment by TheDrone7** [comment]
Please specify the version to be 4.2.7 as the latest 5.0.0 is a bit unstable. There are more known issues.

**Comment by Dig0w** [comment]
ok thanks
